### PR TITLE
feat(test): Test in node 0.12

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by TDA** [comment]
thanks @shane-tomlinson !

**Comment by jrgm** [comment]
It's not specific to this bug, but I have forgotten to mention it earlier, so doing so now. While it's nice to test on node 0.12, we should be testing on iojs (and not iojs-v1 or iojs-v2, just iojs, latest), which will be 3.0.0 Real Soon Now).

**Comment by jrgm** [comment]
Actually, that comment was really off-topic. Sorry about that.

**Comment by pdehaan** [comment]
> @jrgm: we should be testing on iojs



---

**Futher offtopic:** We should probably audit all the .travis.yml in all the fxa-\* repos one of these days. I keep meaning to write a script that will just cURL all those files from GitHub and display them in a list so we can side-by-side compare them.

**Pull request merged**
